In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [26]:
# import the json file
dir = os.getcwd()
df = pd.read_json(dir[:-3]+"data\data.json", orient="index")
df.head()

,listing_id,title,type,available,sold,price_original,price_idr,shipping_price_original,shipping_location,return,seller,condition
0,354907151520,"Microsoft 13"" Surface Pro 8 (i5, 8GB RAM, 256G...",Laptops & Netbooks,Limited quantity available,1,US $669.99,"IDR9,999,850.75",US $54.46,"Avenel, New Jersey, United States",30 days returns,Always Deals Store,New
1,333563280818,CHUWI Laptop HeroBook GemiBook CoreBook Pro/Pl...,Laptops & Netbooks,Limited quantity available,32,EUR 239.99,"IDR4,026,996.38",Free,None,30 days returns,CHUWI Official Store（chuwi2018）,New
2,333996205343,"CHUWI HeroBook Pro 14.1"" Windows 10 Laptop Int...",Laptops & Netbooks,Limited quantity available,14,EUR 199.99,"IDR3,355,802.35",Free,None,30 days returns,CHUWI Official Store（chuwi2018）,New
3,295671743764,"HP Omen 17.3"" Gaming Notebook QHD 165Hz i9-139...",Laptops & Netbooks,Limited quantity available,92,"US $2,499.99","IDR37,313,283.58",None,"Atlanta, Georgia, United States",30 days returns,Antonline,New
4,285185433173,"Lenovo ThinkPad P1 Gen 5 15.6"" 2022 2K 2.3GHz ...",Laptops & Netbooks,Limited quantity available,5,"US $1,399.99","IDR20,895,373.13",US $168.15,"Sanford, Florida, United States",30 days returns,ItsWorthMore,Excellent - Refurbished

In [27]:
# Seperate currency 

priceOriCurrArr = list()
priceOriValArr = list()
shipAvailabilityArr = list()
shipPriceCurrArr = list()
shipPriceValArr = list()

for i in range(len(df)):
    # Make sure listing_id is an int
    df.iloc[i,0] = int(df.iloc[i,0])

    # Seperate price_original
    price_ori = df.iloc[i, 5].replace(",","")
    alreadyFound = False
    lastIdx = len(price_ori)
    firstIdx = 0
    for j in range(len(price_ori)):        
        if (price_ori[j].isnumeric()):
            if (not alreadyFound):
                firstIdx = j
                alreadyFound = True
        else:
            if (alreadyFound and price_ori[j] != "."):
                lastIdx = j
                alreadyFound = False

    priceOriCurrArr.append(price_ori[:firstIdx])
    priceOriValArr.append(float(price_ori[firstIdx:lastIdx]))

    # Make sure sold is an int
    sold_attrib = df.iloc[i,4]
    if (sold_attrib is not None):
        df.iloc[i,4] = int(sold_attrib.replace(",",""))

    # Delete currency in price_idr
    df.iloc[i,6] = float(df.iloc[i,6][3:].replace(",",""))

    # Seperate for shipping_price
    ship_price = df.iloc[i,7]
    if (ship_price == None):
        shipAvailabilityArr.append(False)
        shipPriceCurrArr.append(None)
        shipPriceValArr.append(None)
    elif (ship_price == "Free"):
        shipAvailabilityArr.append(True)
        shipPriceCurrArr.append(None)
        shipPriceValArr.append(0.0)
    else :
        shipAvailabilityArr.append(True)
        alreadyFound = False
        lastIdx = len(ship_price)
        firstIdx = 0
        ship_price = ship_price.replace(",","")
        for j in range(len(ship_price)):
            if (ship_price[j].isnumeric()):
                if (not alreadyFound):
                    firstIdx = j
                    alreadyFound = True
            else:
                if (alreadyFound and ship_price[j] != "."):
                    lastIdx = j
                    alreadyFound = False

        shipPriceCurrArr.append(ship_price[:firstIdx])
        shipPriceValArr.append(float(ship_price[firstIdx:lastIdx]))

df['price_original_currency'] = priceOriCurrArr
df['price_original_value'] = priceOriValArr
df['shipping_availability'] = shipAvailabilityArr
df['shipping_price_currency'] = shipPriceCurrArr
df['shipping_price_value'] = shipPriceValArr
df.head()

,listing_id,title,type,available,sold,price_original,price_idr,shipping_price_original,shipping_location,return,seller,condition,price_original_currency,price_original_value,shipping_availability,shipping_price_currency,shipping_price_value
0,354907151520,"Microsoft 13"" Surface Pro 8 (i5, 8GB RAM, 256G...",Laptops & Netbooks,Limited quantity available,1,US $669.99,9999850.75,US $54.46,"Avenel, New Jersey, United States",30 days returns,Always Deals Store,New,US $,669.99,True,US $,54.46
1,333563280818,CHUWI Laptop HeroBook GemiBook CoreBook Pro/Pl...,Laptops & Netbooks,Limited quantity available,32,EUR 239.99,4026996.38,Free,None,30 days returns,CHUWI Official Store（chuwi2018）,New,EUR,239.99,True,None,0.00
2,333996205343,"CHUWI HeroBook Pro 14.1"" Windows 10 Laptop Int...",Laptops & Netbooks,Limited quantity available,14,EUR 199.99,3355802.35,Free,None,30 days returns,CHUWI Official Store（chuwi2018）,New,EUR,199.99,True,None,0.00
3,295671743764,"HP Omen 17.3"" Gaming Notebook QHD 165Hz i9-139...",Laptops & Netbooks,Limited quantity available,92,"US $2,499.99",37313283.58,None,"Atlanta, Georgia, United States",30 days returns,Antonline,New,US $,2499.99,False,None,NaN
4,285185433173,"Lenovo ThinkPad P1 Gen 5 15.6"" 2022 2K 2.3GHz ...",Laptops & Netbooks,Limited quantity available,5,"US $1,399.99",20895373.13,US $168.15,"Sanford, Florida, United States",30 days returns,ItsWorthMore,Excellent - Refurbished,US $,1399.99,True,US $,168.15

In [28]:
# Drop unused attributes
df = df.drop(['price_original', 'shipping_price_original'],axis = 1)
df.head()

,listing_id,title,type,available,sold,price_idr,shipping_location,return,seller,condition,price_original_currency,price_original_value,shipping_availability,shipping_price_currency,shipping_price_value
0,354907151520,"Microsoft 13"" Surface Pro 8 (i5, 8GB RAM, 256G...",Laptops & Netbooks,Limited quantity available,1,9999850.75,"Avenel, New Jersey, United States",30 days returns,Always Deals Store,New,US $,669.99,True,US $,54.46
1,333563280818,CHUWI Laptop HeroBook GemiBook CoreBook Pro/Pl...,Laptops & Netbooks,Limited quantity available,32,4026996.38,None,30 days returns,CHUWI Official Store（chuwi2018）,New,EUR,239.99,True,None,0.00
2,333996205343,"CHUWI HeroBook Pro 14.1"" Windows 10 Laptop Int...",Laptops & Netbooks,Limited quantity available,14,3355802.35,None,30 days returns,CHUWI Official Store（chuwi2018）,New,EUR,199.99,True,None,0.00
3,295671743764,"HP Omen 17.3"" Gaming Notebook QHD 165Hz i9-139...",Laptops & Netbooks,Limited quantity available,92,37313283.58,"Atlanta, Georgia, United States",30 days returns,Antonline,New,US $,2499.99,False,None,NaN
4,285185433173,"Lenovo ThinkPad P1 Gen 5 15.6"" 2022 2K 2.3GHz ...",Laptops & Netbooks,Limited quantity available,5,20895373.13,"Sanford, Florida, United States",30 days returns,ItsWorthMore,Excellent - Refurbished,US $,1399.99,True,US $,168.15

In [29]:
# Erase "available" in available and "returns" in returns

for i in range(len(df)):
    if (df.iloc[i,3] is not None):
        df.iloc[i,3] = df.iloc[i,3].replace("available", "")
    if (df.iloc[i,7]  is not None):
        df.iloc[i,7] = df.iloc[i,7].replace("returns", "")

df.head()

,listing_id,title,type,available,sold,price_idr,shipping_location,return,seller,condition,price_original_currency,price_original_value,shipping_availability,shipping_price_currency,shipping_price_value
0,354907151520,"Microsoft 13"" Surface Pro 8 (i5, 8GB RAM, 256G...",Laptops & Netbooks,Limited quantity,1,9999850.75,"Avenel, New Jersey, United States",30 days,Always Deals Store,New,US $,669.99,True,US $,54.46
1,333563280818,CHUWI Laptop HeroBook GemiBook CoreBook Pro/Pl...,Laptops & Netbooks,Limited quantity,32,4026996.38,None,30 days,CHUWI Official Store（chuwi2018）,New,EUR,239.99,True,None,0.00
2,333996205343,"CHUWI HeroBook Pro 14.1"" Windows 10 Laptop Int...",Laptops & Netbooks,Limited quantity,14,3355802.35,None,30 days,CHUWI Official Store（chuwi2018）,New,EUR,199.99,True,None,0.00
3,295671743764,"HP Omen 17.3"" Gaming Notebook QHD 165Hz i9-139...",Laptops & Netbooks,Limited quantity,92,37313283.58,"Atlanta, Georgia, United States",30 days,Antonline,New,US $,2499.99,False,None,NaN
4,285185433173,"Lenovo ThinkPad P1 Gen 5 15.6"" 2022 2K 2.3GHz ...",Laptops & Netbooks,Limited quantity,5,20895373.13,"Sanford, Florida, United States",30 days,ItsWorthMore,Excellent - Refurbished,US $,1399.99,True,US $,168.15

In [30]:
# Drop duplicates product
cols = df.columns.tolist()
cols.remove("type")

df = df.drop_duplicates(subset=cols)
df.head()

,listing_id,title,type,available,sold,price_idr,shipping_location,return,seller,condition,price_original_currency,price_original_value,shipping_availability,shipping_price_currency,shipping_price_value
0,354907151520,"Microsoft 13"" Surface Pro 8 (i5, 8GB RAM, 256G...",Laptops & Netbooks,Limited quantity,1,9999850.75,"Avenel, New Jersey, United States",30 days,Always Deals Store,New,US $,669.99,True,US $,54.46
1,333563280818,CHUWI Laptop HeroBook GemiBook CoreBook Pro/Pl...,Laptops & Netbooks,Limited quantity,32,4026996.38,None,30 days,CHUWI Official Store（chuwi2018）,New,EUR,239.99,True,None,0.00
2,333996205343,"CHUWI HeroBook Pro 14.1"" Windows 10 Laptop Int...",Laptops & Netbooks,Limited quantity,14,3355802.35,None,30 days,CHUWI Official Store（chuwi2018）,New,EUR,199.99,True,None,0.00
3,295671743764,"HP Omen 17.3"" Gaming Notebook QHD 165Hz i9-139...",Laptops & Netbooks,Limited quantity,92,37313283.58,"Atlanta, Georgia, United States",30 days,Antonline,New,US $,2499.99,False,None,NaN
4,285185433173,"Lenovo ThinkPad P1 Gen 5 15.6"" 2022 2K 2.3GHz ...",Laptops & Netbooks,Limited quantity,5,20895373.13,"Sanford, Florida, United States",30 days,ItsWorthMore,Excellent - Refurbished,US $,1399.99,True,US $,168.15

In [31]:
# Split the original dataframe into three dfs
product = df[['listing_id','title', 'type', 'available', 'sold', 'return', 'seller', 'condition']]
price = df[['price_original_currency', 'price_original_value', 'price_idr']]
shipment = df[['shipping_availability', 'shipping_price_currency', 'shipping_price_value', 'shipping_location']]

In [32]:
dir = os.getcwd()
product.to_json(dir[:-3]+"data\data_product.json", orient='index', indent=2)
price.to_json(dir[:-3]+"data\data_price.json", orient='index', indent=2)
shipment.to_json(dir[:-3]+"data\data_shipment.json", orient='index', indent=2)